### ISSUE TITLE
Replay deletion

### ISSUE THREAD

**Issue by Azathoth2k** [Kevin-OConnor/PiScout-2016#36]
It looks like there is an issue with the replay record deletion code in server.py

            if d['Replay']:   #replay
                cursor.execute('DELETE from scout WHERE Team=? AND Match=?', (str(d[0]),str(d[1])))

Shouldn't this be 

cursor.execute('DELETE from scout WHERE Team=? AND Match=?',
                               (str(d['Team']), str(d['Match'])))

Thx

**Comment by Kevin-OConnor** [comment]
Yes, it should be, it looks like I managed to miss that during the abstraction rewrites this summer/fall. Thanks!

I'm working on testing our 2018 match sheet updates right now. I will merge this fix as soon as I get done with that.

**Comment by Kevin-OConnor** [comment]
It looks like I fixed this in f3f65ed when I heavily edited that section while adding Pit Scouting capability. Sorry for not keeping things clean in a way that would make it easy to cherrypick if you've already forked and started working on 2018 game specifics.

**Comment by Azathoth2k** [comment]
No worries, it was a small adjustment.


Thanks,


Keith



-----Original Message-----
