### ISSUE TITLE
Scanning program doesn't appear to start

### ISSUE THREAD

**Issue by cjdenio** [Kevin-OConnor/PiScout-2016#51]
After starting PiScout using the `RunLocal.bat` file, two console windows do indeed pop up. However, one of them is stuck on `PiScout Starting`. Also, nothing seems to happen when adding a `.pdf` file to the `Sheets` folder. I've installed all of the required dependencies. What could be going on? Thank you!

**Comment by Kevin-OConnor** [comment]
"PiScout starting" is all it prints when it starts. The program processes images so it currently looks only for .jpg or.png files. If you can get it working with PDF or other file types feel free to PR!

**Comment by cjdenio** [comment]
Ah. Thank you!

**Comment by cjdenio** [comment]
Now, after adding a `.jpg` file, the program shuts down after displaying this error. The web server program continues to run, though.
![screenshot 1](https://user-images.githubusercontent.com/34525547/52918760-c0bd7300-32c8-11e9-928f-54d48558a512.png)
